apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: server-node
        image: gcr.io/sopes-295304/node:1.0
        ports:
        - containerPort: 5000
      - name: server-web
        image: gcr.io/sopes-295304/web:1.0
        ports:
        - containerPort: 3000
