apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:  
  rules:
  - http:
      ports:
      - port: 85
      paths:
      - backend:
          serviceName: grpc-deployment
          servicePort: 9000