apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: gloo-ingress
 annotations:
    kubernetes.io/ingress.class: gloo
spec:  
  tls:
  - hosts:
    - gloo.proyecto2.com
    secretName: my-tls-secret
  rules:
  - host: gloo.proyecto2.com
    http:
      paths:
      - path: /.*
        backend:
          serviceName: rabbit-deployment
          servicePort: 7000