apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gloo-ingress
  annotations:
    kubernetes.io/ingress.class: gloo
spec:  
  rules:
  - http:
      paths:
      - backend:
          serviceName: grpc-deployment
          servicePort: 9000