version: "3.2"
services:
    rabbitmq-server:
        image: "rabbitmq"
        ports: 
          - 5672:5672
          - 15672:15672

    go-service:
        build: ./go-service
        depends_on:
            - rabbitmq-server
        ports:
            - "3000:3000"


